title: Hype
email: your-email@example.com
description: This is my blog
destination: docs
incremental: false
baseurl: ""
#baseurl: "/FrontEnd-Project-Hype"
url: ""
twitter_username: jekyllrb
github_username:  jekyll
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md]

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
